spring:
  application:
    name: recipeSharingAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes_db
    username: postgres
    password: Mg505!9405
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8070